apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: component-byk-resql
spec:
  host: component-byk-resql
  subsets:
  - name: component-byk-resql
    labels:
      app: component-byk-resql
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: component-byk-resql
spec:
  hosts:
  - component-byk-resql
  http:
  - name: allow
    match:
    - sourceLabels:
        app: component-byk-ruuter
    - sourceLabels:
        app: component-byk-ruuter-private
    route:
    - destination:
        host: component-byk-resql
        subset: component-byk-resql
  - name: reject
    route:
    - destination:
        host: component-byk-resql
        subset: component-byk-resql
    fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 403
