apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
        - name: init-copy-files
          image: "{{ .Values.images.dsl.registry }}/{{ .Values.images.dsl.repository }}:{{ .Values.images.dsl.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              pwd
              cp -r ../Ruuter/ /app/DSL
              cp -r ../Resql/ /app/DSL
              cp -r ../DataMapper/ /app/DSL
              cp -r ../Ruuter/ /opt/dsl
              cp -r ../Resql/ /opt/dsl
              cp -r ../DataMapper/ /opt/dsl
              ls -la 
          volumeMounts:
            - name: services-dsl
              mountPath: /app/DSL
            - name: dsl
              mountPath: /data
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.gui.registry }}/{{ .Values.images.gui.repository }}:{{ .Values.images.gui.tag }}"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_API_URL }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: CHOKIDAR_USEPOLLING
              value: "{{ .Values.env.CHOKIDAR_USEPOLLING }}"
            - name: REACT_APP_API_URL
              value: "{{ .Values.env.REACT_APP_API_URL }}"
            - name: REACT_APP_BUEROKRATT_CHATBOT_URL
              value: "{{ .Values.env.REACT_APP_BUEROKRATT_CHATBOT_URL }}"
            - name: REACT_APP_OPENSEARCH_DASHBOARD_URL
              value: "{{ .Values.env.REACT_APP_OPENSEARCH_DASHBOARD_URL }}"
            - name: REACT_APP_OPENDATAPORT_URL
              value: "{{ .Values.env.REACT_APP_OPENDATAPORT_URL }}"
            - name: REACT_APP_RUUTER_V2_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_PRIVATE_API_URL }}"
            - name: REACT_APP_RUUTER_V2_ANALYTICS_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_V2_ANALYTICS_API_URL }}"
            - name: REACT_APP_MENU_URL
              value: "{{ .Values.env.REACT_APP_MENU_URL }}"
            - name: REACT_APP_MENU_PATH
              value: "{{ .Values.env.REACT_APP_MENU_PATH }}"
            - name: REACT_APP_AUTH_BASE_URL
              value: "{{ .Values.env.REACT_APP_AUTH_BASE_URL }}"
            - name: REACT_APP_APP_PORT
              value: "{{ .Values.env.REACT_APP_APP_PORT }}"
            - name: REACT_APP_LOCAL
              value: "{{ .Values.env.REACT_APP_LOCAL }}"
            - name: REACT_APP_AUTH_PATH
              value: "{{ .Values.env.REACT_APP_AUTH_PATH }}"
            - name: REACT_APP_DOCKER_RUUTER
              value: "{{ .Values.env.REACT_APP_DOCKER_RUUTER }}"
            - name: REACT_APP_CUSTOMER_SERVICE_LOGIN
              value: "{{ .Values.env.REACT_APP_CUSTOMER_SERVICE_LOGIN }}"
            - name: REACT_APP_CONVERSATIONS_BASE_URL
              value: "{{ .Values.env.REACT_APP_CONVERSATIONS_BASE_URL }}"
            - name: REACT_APP_TRAINING_BASE_URL
              value: "{{ .Values.env.REACT_APP_TRAINING_BASE_URL }}"
            - name: REACT_APP_ANALYTICS_BASE_URL
              value: "{{ .Values.env.REACT_APP_ANALYTICS_BASE_URL }}"
            - name: REACT_APP_SERVICES_BASE_URL
              value: "{{ .Values.env.REACT_APP_SERVICES_BASE_URL }}"
            - name: REACT_APP_SETTINGS_BASE_URL
              value: "{{ .Values.env.REACT_APP_SETTINGS_BASE_URL }}"
            - name: REACT_APP_MONITORING_BASE_URL
              value: "{{ .Values.env.REACT_APP_MONITORING_BASE_URL }}"
            - name: REACT_APP_SERVICE_ID
              value: "{{ .Values.env.REACT_APP_SERVICE_ID }}"
            - name: REACT_APP_RUUTER_PRIVATE_API_URL
              value: "{{ .Values.env.REACT_APP_RUUTER_PRIVATE_API_URL }}"
          volumeMounts:
            - name: services-dsl
              mountPath: /DSL/
      volumes:
        - name: services-dsl
          emptyDir: {}
#          persistentVolumeClaim:
#            claimName: pvc-services-dsl
        - name: dsl
          emptyDir: {}


