imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer

release_name: "module-byk-training-gui"
  
images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/training-module"
    tag: "pre-alpha-clean-1.15.2"
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-pre-alpha-1.2.5" # TODO: Change this to the correct tag

env:
  REACT_APP_RUUTER_API_URL: "https://ruuter.test.buerokratt.ee/v2/private/backoffice"
  NODE_ENV: "development"
  CHOKIDAR_USEPOLLING: "true"
  REACT_APP_API_URL: "https://ruuter.test.buerokratt.ee/v2/private/training"
  REACT_APP_BUEROKRATT_CHATBOT_URL: "http://byk-bot:5005"
  REACT_APP_OPENSEARCH_DASHBOARD_URL: "https://opensearch.org/"
  REACT_APP_OPENDATAPORT_URL: "https://avaandmed.eesti.ee"
  REACT_APP_RUUTER_V2_PRIVATE_API_URL: "https://ruuter.test.buerokratt.ee/v2/private/backoffice"
  REACT_APP_RUUTER_V2_ANALYTICS_API_URL: "https://ruuter.test.buerokratt.ee/v2/private/analytics"
  REACT_APP_MENU_URL: "https://admin.test.buerokratt.ee"
  REACT_APP_MENU_PATH: "/chat/menu.json"
  REACT_APP_AUTH_BASE_URL: "https://ruuter.test.buerokratt.ee"
  REACT_APP_APP_PORT: "3001"
  REACT_APP_LOCAL: "false"
  REACT_APP_AUTH_PATH: "/v2/private/backoffice/custom-jwt/userinfo"
  REACT_APP_DOCKER_RUUTER: "http://byk-ruuter-private:8080"
  REACT_APP_CUSTOMER_SERVICE_LOGIN: "http://admin.test.buerokratt.ee/et/dev-auth"
  REACT_APP_CONVERSATIONS_BASE_URL: "https://admin.test.buerokratt.ee/chat"
  REACT_APP_TRAINING_BASE_URL: "https://admin.test.buerokratt.ee/training"
  REACT_APP_ANALYTICS_BASE_URL: "https://admin.test.buerokratt.ee/analytics"
  REACT_APP_SERVICES_BASE_URL: "https://admin.test.buerokratt.ee/services"
  REACT_APP_SETTINGS_BASE_URL: "https://admin.test.buerokratt.ee/settings"
  REACT_APP_MONITORING_BASE_URL: "https://admin.test.buerokratt.ee/monitoring"
  REACT_APP_SERVICE_ID: "training"
  REACT_APP_RUUTER_PRIVATE_API_URL: "https://ruuter.test.buerokratt.ee/v2/private/backoffice"

liquibase:
  jdbcUrl: "jdbc:postgresql://databases-users-db:5432/byk?user=byk"    
  dbPassword: "01234"  
