apiVersion: batch/v1
kind: Job
metadata:
  name: training-liquibase
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: training-liquibase
    spec:
      initContainers:
        - name: init-copy-files-liquibase
          image: "{{ .Values.images.dsl.registry }}/{{ .Values.images.dsl.repository }}:{{ .Values.images.dsl.tag }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              pwd
              cp -r ../Liquibase/training /app/DSL
              ls -la /app/DSL/training
          volumeMounts:
            - name: liquibase
              mountPath: /app/DSL
      containers:
        - name: training-liquibase
          image: liquibase/liquibase:4.23.2
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /DSL && cd /DSL/training &&
              liquibase
              --url={{ .Values.liquibase.jdbcUrl }}
              --password={{ .Values.liquibase.dbPassword }} --changeLogFile=changelog.yaml update
          volumeMounts:
            - name: liquibase
              mountPath: /DSL/

      volumes:
      - name: liquibase
        emptyDir: {}
      restartPolicy: Never