imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: DOMAIN.buerokratt.ee # Domain name

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "component-opensearch-node"  

images:
  scope:
    image: opensearchproject/opensearch:1.3.16
  opensearch:
    backoffice:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL/OpenSearch
    services:
      repo: https://github.com/buerokratt/Service-Module.git
      path: DSL/OpenSearch
    training:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/OpenSearch
    common:
      repo: https://github.com/buerokratt/Common-Services
      path: DSL/OpenSearch

env:
  CLUSTER_NAME: "opensearch-cluster"
  NODE_NAME: "component-opensearch-node"
  DISCOVERY_TYPE: "single-node"
  BOOTSTRAP_MEMORY_LOCK: "true"
  OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
  DISABLE_INSTALL_DEMO_CONFIG: "true"
  DISABLE_SECURITY_PLUGIN: "true"
