
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: DOMAIN.buerokratt.ee # Domain name

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "component-byk-dmapper"
      

images:
  scope:
    registry: "ghcr.io"
    repository: buerokratt/datamapper
    tag: pre-alpha-test-2.1.13
#    repository: "varmoh/buerokratt-data-mapper"
#    tag: "pre-alpha-test-2.5.1" # Images (tags) are up to date, currently no changes needed
  backoffice:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "backoffice-module-test-1.1.241" # Images (tags) are up to date, currently no changes needed
  analytics:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "analytics-module-test-1.2.3" # Images (tags) are up to date, currently no changes needed
  services:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "service-module-test-1.2.3" # Images (tags) are up to date, currently no changes needed
  training:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-test-1.1.79" # Images (tags) are up to date, currently no changes needed 
  pipelines:
    service:
      repo: https://github.com/buerokratt/Service-Module.git
      path: /DSL
  bot:
    dsl:
      repo: https://github.com/buerokratt/Training-Module.git
      path: DSL/DMapper/locations
  commonservice:
    dsl:
      repo: https://github.com/buerokratt/Common-Services.git
      path: /