
apiVersion: batch/v1
kind: Job
metadata:
  name: "job-{{ .Values.release_name }}-notification"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "job-{{ .Values.release_name }}-notification"
    spec:
      initContainers:
       - name: opensearch-clone-notification
         image: alpine/git:2.36.3
         volumeMounts:
            - name: opensearch-repos
              mountPath: /root/backoffice
         command: ["/bin/sh"]
         args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              cp -r /tmp/dsl-source/$DSL_PATH/fieldMappings /root/backoffice/ &&
              cp -r /tmp/dsl-source/$DSL_PATH/mock /root/backoffice/ &&
              cp -r /tmp/dsl-source/$DSL_PATH/deploy-opensearch.sh /root/backoffice/ &&
              echo 'moved' &&
              ls /root/backoffice
         env:
            - name: DSL_REPO
              value: {{ .Values.images.opensearch.backoffice.repo }}
            - name: DSL_PATH
              value: {{ .Values.images.opensearch.backoffice.path }}

      containers:
        - name: opensearch-update-notification
          image: alpine
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              apk add curl &&
              cd /backoffice &&
              sh deploy-opensearch.sh http://component-opensearch-node:9200 admin:admin
          volumeMounts:
            - name: opensearch-repos
              mountPath: /backoffice

      volumes:
        - name: opensearch-repos
          emptyDir: {}
      restartPolicy: Never
