{{- if not .Release.IsUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "job-{{ .Values.release_name }}-services"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "job-{{ .Values.release_name }}-services"
    spec:
      initContainers:
       - name: opensearch-clone-services
         image: alpine/git:2.36.3
         volumeMounts:
            - name: opensearch-repos
              mountPath: /root/services
         command: ["/bin/sh"]
         args:
            - "-c"
            - >
              git clone $DSL_REPO /tmp/dsl-source &&
              echo 'downloaded' &&
              cp -r /tmp/dsl-source/$DSL_PATH/fieldMappings /root/services/ &&
              cp -r /tmp/dsl-source/$DSL_PATH/mock /root/services/ &&
              cp -r /tmp/dsl-source/$DSL_PATH/templates /root/services/ &&
              cp -r /tmp/dsl-source/$DSL_PATH/deploy-opensearch.sh /root/services/ &&
              echo 'moved' &&
              ls /root/services
         env:
            - name: DSL_REPO
              value: {{ .Values.images.opensearch.services.repo }}
            - name: DSL_PATH
              value: {{ .Values.images.opensearch.services.path }}
      containers:      
       - name: opensearch-update-services
         image: alpine
         command: ["/bin/sh"]
         args:
            - "-c"
            - >
              apk add curl &&
              cd /services &&
              sh deploy-opensearch.sh http://component-opensearch-node:9200 admin:admin
         volumeMounts:
            - name: opensearch-repos
              mountPath: /services

      volumes:
        - name: opensearch-repos
          emptyDir: {}
      restartPolicy: Never
{{- end }}

