apiVersion: v1
kind: ConfigMap
metadata:
  name: widget-index-config
data:
  index.html: |-
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Title</title>
    </head>
    <body>
    <div id="byk-va"></div>
    <script>
      window._env_ = {
        RUUTER_API_URL: 'https://ruuter.test.buerokratt.ee/v2/public/backoffice',
        NOTIFICATION_NODE_URL: 'https://ruuter.test.buerokratt.ee',
        TIM_AUTHENTICATION_URL: 'https://tim.test.buerokratt.ee/oauth2/authorization/tara?callback_url=https://test.buerokratt.ee',
        OFFICE_HOURS: {
          TIMEZONE: 'Europe/Tallinn',
          BEGIN: 0,
          END: 24,
          DAYS: [1, 2, 3, 4, 5, 6, 7],
        },
      };
    </script>
    <script id="script-bundle" type="text/javascript" src="./widget_bundle.js" crossorigin=""></script>
    </body>
    <style>
      .background {
        background: #004d40;
        width: 100vw;
        height: 100vh;
      }
    </style>
    </html>
  env-config.js: |2
      window._env_ = {
        RUUTER_API_URL: 'https://ruuter.test.buerokratt.ee/v2/public/backoffice',
        NOTIFICATION_NODE_URL: 'https://ruuter.test.buerokratt.ee',
        TIM_AUTHENTICATION_URL: 'https://tim.test.buerokratt.ee/oauth2/authorization/tara?callback_url=https://test.buerokratt.ee',
        OFFICE_HOURS: {
          TIMEZONE: 'Europe/Tallinn',
          BEGIN: 0,
          END: 24,
          DAYS: [1, 2, 3, 4, 5, 6, 7],
        },
      };