apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: byk-widget-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  labels:
    name: byk-widget-ingress
spec:
  rules:
    - host: { { .Values.domain } }
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "{{ .Values.release_name }}"
                port:
                  number: 3003
  tls:
    - hosts:
        - { { .Values.domain } }
      secretName: test.buerokratt.ee0503prod
