apiVersion: v1
kind: ConfigMap
metadata:
  name: constant-config
data:
  default.conf: |
      server {
      server_name localhost;
      listen 443;

      server_tokens off;
      add_header Content-Security-Policy "upgrade-insecure-requests; default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://ruuter.test.buerokratt.ee/v2/public/ https://tim.test.buerokratt.ee/ https://admin.test.buerokratt.ee/ https://ruuter.test.buerokratt.ee/v2/private/;";

      location / {
        root /usr/share/nginx/html/customer-service;
        try_files $uri /index.html;
      }

      location /status {
        access_log off;
        default_type text/plain;
        add_header Content-Type text/plain;
        return 200 "alive";
      }
      }
      server {
      listen 80;
      server_name localhost;
      return 301 https://$host$request_uri;
      }

  env-config.js: |
    window._env_ = {
      "RUUTER_API_URL": "https://ruuter.test.buerokratt.ee/v2/public/backoffice",
      "TIM_API_URL": "https://tim.test.buerokratt.ee",
      "TARA_REDIRECT_URL": "https://tim.test.buerokratt.ee/oauth2/authorization/tara?callback_url=https://admin.test.buerokratt.ee/auth/callback",
      "MONITORING_URL": "https://MONITORING_URL",
      "PASSWORD_AUTH_ENABLED": true,
      "BACKOFFICE_URL": "https://admin.test.buerokratt.ee/chat",
      "INSTITUTION_FORWARDING_ENABLED": true,
      "AUTHORITY_NAME": 'TEST BYK',

    };