imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: DOMAIN.buerokratt.ee # Domain name
secretname: admin.DOMAIN.buerokratt.ee1707 # Cert name value, change this as suited to environment

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "module-byk-authentication-layer"

images:
  gui:
    registry: "ghcr.io"
    repository: "buerokratt/authentication-layer"
    tag: "pre-alpha-test-1.2.0" # Images (tags) are up to date, currently no changes needed
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "pre-alpha-1.1.0" # Images (tags) are up to date, currently no changes needed
