imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: stage.buerokratt.ee # Domain name
releaseName: "component-databases"

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up differents

tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "t9n5Kmm7vP9" # Change password accordingly, make sure that ths passord you set here, will be used inside values.yaml under component TIM values.yaml
    database: tim
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true

users-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "PASSWORD" # Change password accordingly, make sure that ths passord you set here, will be used inside values.yaml in components and modules, where necessary.
    database: byk
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true
      