imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # Domain name

ingress:
  certIssuerName: letsencrypt-prod # Change this if your certIssuerName has set up different

release_name: "component-byk-dmapper-v1"
  
images:
  scope:
    image: opensearchproject/opensearch:latest
  pipelines:
    training:
      repo: https://github.com/buerokratt/Training-Module.git
      path: /
  dsl:
    registry: "ghcr.io"
    repository: "buerokratt/buerokratt-dsl"
    tag: "training-module-pre-alpha-1.4.25" # Images (tags) are up to date, currently no changes needed

liquibase:
  jdbcUrl: "jdbc:postgresql://databases-users-db:5432/byk?user=byk"    
  dbPassword: "01234"  # Change password accordingly